export const genres = [
  { id: 28, val: 'Action', color: 'red' },
  { id: 12, val: 'Adventure', color: 'blue' },
  { id: 16, val: 'Animation', color: 'yellow' },
  { id: 35, val: 'Comedy', color: 'green' },
  { id: 80, val: 'Crime', color: 'gray' },
  { id: 99, val: 'Documentary', color: 'white' },
  { id: 18, val: 'Drama', color: 'pink' },
  { id: 10751, val: 'Family', color: 'lightblue' },
  { id: 14, val: 'Fantasy', color: 'purple' },
  { id: 36, val: 'History', color: 'darkgrey' },
  { id: 27, val: 'Horror', color: 'red' },
  { id: 10402, val: 'Music', color: 'purple' },
  { id: 9648, val: 'Mystery', color: 'blue' },
  { id: 10749, val: 'Romance', color: 'pink' },
  { id: 878, val: 'Science Fiction', color: 'lightblue' },
  { id: 10770, val: 'TV Movie', color: 'black' },
  { id: 53, val: 'Thriller', color: 'green' },
  { id: 10752, val: 'War', color: 'gray' },
  { id: 37, val: 'Western', color: 'yellow' },
]